In [1]:
library(tidyverse)
library(tidymodels)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
── Attaching packages ────────────────────────────────────── tidymodels 1.1.1 ──

✔ broom        1.0.6     ✔ rsample      1.2.1
✔ dials        1.3.0     ✔ tune         1.1.2
✔ infer        1.0.7     ✔ workflows    1.1.4
✔ modeldata    1.4.0     ✔ workflowsets 1.0.1
✔ parsnip      1.2.1     ✔ yardstick    1.3.1
✔ recipes      1.1.0

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/

In [43]:
players <- read_csv("../data/players.csv")

head(players)

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

In [44]:
players <- players |>
                mutate(experience = factor(experience, levels = c("Beginner", "Amateur", "Regular", "Veteran", "Pro"))) |>
                filter(!is.na(Age)) |>
                mutate(ages_0_10 = as.numeric(Age < 10)) |>
                mutate(ages_10_15 = as.numeric(10 <= Age & Age < 15)) |>
                mutate(ages_15_20 = as.numeric(15 <= Age & Age < 20)) |>
                mutate(ages_20_25 = as.numeric(20 <= Age & Age < 25)) |>
                mutate(ages_25_30 = as.numeric(25 <= Age & Age < 30)) |>
                mutate(ages_30plus = as.numeric(30 <= Age)) |>
                select(-hashedEmail, -name, -gender, -Age) |>
                mutate(subscribe = as.numeric(subscribe)) |>
                mutate(experience = as.numeric(experience))

players

    experience subscribe played_hours ages_0_10 ages_10_15 ages_15_20
1   5          1         30.3         1         0          0
2   4          1          3.8         0         0          1
3   4          0          0.0         0         0          1
4   2          1          0.7         0         0          0
5   3          1          0.1         0         0          0
6   2          1          0.0         0         0          1
7   3          1          0.0         0         0          1
8   2          0          0.0         0         0          0
9   2          1          0.1         0         0          0
10  4          1          0.0         0         0          0
11  4          1          1.6         0         0          0
12  5          1          0.0         0         0          1
13  1          1          1.5         0         0          0
14  2          1          0.2         0         0          0
15  4          1          0.0         0         0          1
16  2          0          0.0         0         0          0
17  1          1          0.0         0         0          1
18  2          1         48.4         0         0          1
19  2          1          0.5         0         0          1
20  3          1          0.6         0         0          1
21  3          1          0.3         0         0          0
22  2          0          0.1         0         0          1
23  1          1          1.0         0         0          1
24  1          1          0.0         0         0          1
25  2          1          0.7         0         0          0
26  3          1          0.6         0         0          0
27  3          1          0.0         0         0          1
28  4          0          0.0         0         0          0
29  2          1          1.8         0         0          0
30  4          0          0.1         0         0          1
⋮   ⋮          ⋮         ⋮            ⋮         ⋮          ⋮
165 3          1          0.1         0         0          0
166 2          0          1.0         0         0          0
167 1          0          0.3         0         0          1
168 4          1          0.1         0         0          1
169 4          0          0.1         0         0          1
170 5          0          0.4         0         0          0
171 1          0          1.8         0         0          0
172 4          1          0.0         0         0          0
173 3          0          0.0         0         0          0
174 4          1          0.0         0         0          1
175 2          1          0.3         0         0          1
176 5          0          0.0         0         0          1
177 4          0          2.7         0         0          0
178 2          1          0.4         0         0          1
179 4          1          0.1         0         0          1
180 2          0          2.1         0         0          0
181 2          1          0.8         0         0          0
182 5          0          0.2         0         0          1
183 2          1         32.0         0         0          0
184 5          0          1.7         0         0          1
185 3          0          0.1         0         0          1
186 4          1          0.1         0         0          0
187 2          1          0.0         0         0          1
188 1          1          0.0         0         0          1
189 2          0          0.0         0         0          1
190 2          1          0.0         0         0          0
191 2          1          0.0         0         0          1
192 4          0          0.3         0         0          0
193 2          0          0.0         0         0          0
194 2          0          2.3         0         0          1
    ages_20_25 ages_25_30 ages_30plus
1   0          0          0
2   0          0          0
3   0          0          0
4   1          0          0
5   1          0          0
6   0          0          0
7   0          0          0
8   1          0          0
9   0          0          1
10  1          0          0
11  1          0          0
12  0          0          0
13  0          1          0
14  1          0          0
15  0          0          0
16  1          0          0
17  0          0          0
18  0          0          0
19  0          0          0
20  0          0          0
21  0          0          1
22  0          0          0
23  0          0          0
24  0          0          0
25  1          0          0
26  0          1          0
27  0          0          0
28  1          0          0
29  1          0          0
30  0          0          0
⋮   ⋮          ⋮          ⋮
165 1          0          0
166 0          1          0
167 0          0          0
168 0          0          0
169 0          0          0
170 1          0          0
171 0          0          1
172 1          0          0
173 0          0          1
174 0          0          0
175 0          0          0
176 0          0          0
177 1          0          0
178 0          0          0
179 0          0          0
180 1          0          0
181 1          0          0
182 0          0          0
183 1          0          0
184 0          0          0
185 0          0          0
186 0          0          1
187 0          0          0
188 0          0          0
189 0          0          0
190 1          0          0
191 0          0          0
192 1          0          0
193 0          0          1
194 0          0          0

In [56]:
players_split <- initial_split(players, prop = 0.75)
players_train <- training(players_split)
players_test <- testing(players_split)

lr_spec = linear_reg() |>
            set_engine("lm") |>
            set_mode("regression")

recipe <- recipe(played_hours ~ experience + subscribe + ages_30plus + ages_15_20 + ages_20_25 + ages_25_30 + ages_0_10, data = players_train)

players_fit <- workflow() |>
                add_model(lr_spec) |>
                add_recipe(recipe) |>
                fit(data = players_train)

players_fit

══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
0 Recipe Steps

── Model ───────────────────────────────────────────────────────────────────────

Call:
stats::lm(formula = ..y ~ ., data = data)

Coefficients:
(Intercept)   experience    subscribe  ages_30plus   ages_15_20   ages_20_25
      2.411       -0.764        4.761       -0.400        2.746       -1.855
 ages_25_30    ages_0_10
     -2.426       26.948

In [57]:
lm_test_results <- players_fit |>
  predict(players_test) |>
  bind_cols(players_test) |>
  metrics(truth = played_hours, estimate = .pred)

lm_test_results

  .metric .estimator .estimate
1 rmse    standard   40.303781729
2 rsq     standard    0.003200806
3 mae     standard   13.661540040